---

- name: Tasks on a RHEL host
  include_tasks: main-rhel.yml
  when: ansible_distribution == 'RedHat'

- name: Tasks on a CentOS host
  include_tasks: main-centos.yml
  when: ansible_distribution == 'CentOS'

- name: Install Java
  package:
    name: 
      - java
      - unzip
  when: install_requirements
  tags:
  - common

# initscripts are for : v6.x or older
- name: Install initscripts
  package:
    name: initscripts
    state: installed
  tags:
    - common
  when: ansible_distribution_major_version is version_compare('7', '<')

- name: Install PIP dependencies and Remove EPEL
  block:
    - name: Install PIP
      package:
        name: python-pip
        state: installed
      tags:
        - common

    - name: Install Python Dependencies
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - requests
        - lxml
      tags:
        - common

    - name: Remove EPEL Package
      package:
        name: "epel*"
        state: absent
      tags:
        - common
  when: transfer_method == 'csp-to-host' and install_pip_dependencies|bool
