---

- name: Subscribe the host to RHSM
  block:
    - name: Check Pool ID definition
      fail: msg="Extra variable rh_poolid has not been defined. Please add it before running this playbook"
      when: rh_poolid is not defined

    - name: Subscribe the host
      redhat_subscription:
        state: present
        username: "{{ rhn_username }}"
        password: "{{ rhn_password }}"
        autosubscribe: true
        poolids: "{{ rh_poolid }}"
  
  when: rhsm_subscribe_host|bool

- name: Disable All RHEL Repositories
  rhsm_repository:
    name: "*"
    state: disabled
  tags:
    - common
  when: rhsm_disable_existing_repositories|bool

- name: Enable RHEL Repositories
  rhsm_repository:
    name: "{{ rhsm_repositories }}"
    state: enabled
  tags:
    - common
  when: transfer_method == 'csp-to-host' and rhsm_enable_required_repositories|bool

- name: EPEL Configuration
  block:
    - name: Install EPEL for RHEiL
      yum:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
        state: installed
      tags:
        - common
  when: transfer_method == 'csp-to-host' and install_pip_dependencies|bool
